import '@fortawesome/fontawesome-svg-core/styles.css';

import type { Metadata } from 'next';
import { Provider } from '@/components/nextjs/ui/provider';

/**
 * @type {NextJSRootLayoutProps}
 * @summary NextJS root layout component props
 * @description The type definition for the root layout component
 * @author J. Trpka <jtrpka0912@gmail.com>
 * @prop {React.ReactNode} children
 */
type NextJSRootLayoutProps = {
  children: React.ReactNode;
};

/**
 * @constant {Metadata} metadata
 * @summary HTML Metadata
 * @description Metadata object for the NextJS Root Layout
 * @link https://nextjs.org/docs/app/getting-started/metadata-and-og-images#static-metadata
 * @author J. trpka <jtrpka0912@gmail.com>
 */
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/**
 * @function NextJSRootLayout
 * @summary NextJS Root Layout Component
 * @description The NextJS app router root layout.
 * @link https://nextjs.org/docs/app/api-reference/file-conventions/layout#root-layout
 * @link https://nextjs.org/docs/app/getting-started/project-structure
 * @author J. Trpka <jtrpka0912@gmail.com>
 * @param {NextJSRootLayoutProps} props
 * @returns {React.ReactNode}
 */
const NextJSRootLayout = ({ children }: NextJSRootLayoutProps): React.ReactNode => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider enableColorScheme enableSystem={false}>
          {children}
        </Provider>
      </body>
    </html>
  );
};

export default NextJSRootLayout;
