import '../sass/global.scss'; // NOTE: I wonder if I even need SASS with the styling props with Chakra.
import '@fortawesome/fontawesome-svg-core/styles.css';

import type { Metadata } from 'next';
import { Provider } from '@/components/nextjs/ui/provider';
import RootHeader from '@/components/layout/root-layout/root-header/root-header';
import RootFooter from '@/components/layout/root-layout/root-footer/root-footer';

/**
 * @type {RootLayoutProps}
 * @summary Root layout component props
 * @description The type definition for the root layout component
 * @author J. Trpka <jtrpka0912@gmail.com>
 * @prop {React.ReactNode} children
 */
type RootLayoutProps = {
  children: React.ReactNode;
};

/**
 * @constant {Metadata} metadata
 * @summary HTML Metadata
 * @description Metadata object for the root layout
 * @link https://nextjs.org/docs/app/getting-started/metadata-and-og-images#static-metadata
 * @author J. trpka <jtrpka0912@gmail.com>
 */
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/**
 * @function RootLayout
 * @summary Next.JS Root Layout Component
 * @description The main document layout for the NextJS application
 * @link https://nextjs.org/docs/app/api-reference/file-conventions/layout#root-layout
 * @link https://nextjs.org/docs/app/getting-started/project-structure
 * @author J. Trpka <jtrpka0912@gmail.com>
 * @param {RootLayoutProps} props
 * @returns {React.ReactNode}
 */
const RootLayout = ({ children }: RootLayoutProps): React.ReactNode => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider enableColorScheme enableSystem={false}>
          <RootHeader />
          <main>
            {children}
          </main>
          <RootFooter />
        </Provider>
      </body>
    </html>
  );
};

export default RootLayout;
