name: Testing with Jest and Cypress

on:
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Install NPM packages
        run: npm install
      - name: Run Jest and React Testing Library
        run: npm run jest
      - name: Run Cypress
        run: npm run cypress:headless